### ISSUE TITLE
create FIlter

### ISSUE THREAD

**Issue by HalgrimThadeus** [HalgrimThadeus/long-read-microbiome#21]
should contain attributes and filter methods;

**Comment by canerbagci** [comment]
If you feel adventurous: https://docs.oracle.com/javase/8/docs/api/java/util/function/Predicate.html
https://howtodoinjava.com/java-8/how-to-use-predicate-in-java-8/

We might have to switch to this once we have a GUI

**Comment by hannah-frank** [comment]
add more filters (genes, length, GC content, ...) & include in GUI
